language: python
services: 
  - mongodb
  - redis-server
python:
  - "2.6"
  - "2.7"
env:

matrix:

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - python create_db.py --force
  - mkdir filecache
  - chmod -R 0777 filecache 
  - python scrape.py -g 30035
  - python worker.py
  - python clean_db.py

    
script:
    - nosetests 
